<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="obj\Debug\net10.0\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs" />
    <Compile Include="obj\Debug\net10.0\CrudOperation.AssemblyInfo.cs" />
    <Compile Include="obj\Debug\net10.0\CrudOperation.GlobalUsings.g.cs" />
    <Compile Include="obj\Debug\net10.0\CrudOperation.RazorAssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="bin\Debug\net10.0\appsettings.Development.json" />
    <Content Include="bin\Debug\net10.0\appsettings.json" />
    <Content Include="bin\Debug\net10.0\BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.deps.json" />
    <Content Include="bin\Debug\net10.0\BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.runtimeconfig.json" />
    <Content Include="bin\Debug\net10.0\CrudOperation.deps.json" />
    <Content Include="bin\Debug\net10.0\CrudOperation.runtimeconfig.json" />
    <Content Include="bin\Debug\net10.0\CrudOperation.staticwebassets.endpoints.json" />
    <Content Include="bin\Debug\net10.0\CrudOperation.staticwebassets.runtime.json" />
    <Content Include="obj\CrudOperation.csproj.nuget.dgspec.json" />
    <Content Include="obj\Debug\net10.0\ApiEndpoints.json" />
    <Content Include="obj\Debug\net10.0\CrudOperation.csproj.FileListAbsolute.txt" />
    <Content Include="obj\Debug\net10.0\CrudOperation.sourcelink.json" />
    <Content Include="obj\Debug\net10.0\rbcswa.dswa.cache.json" />
    <Content Include="obj\Debug\net10.0\rjimswa.dswa.cache.json" />
    <Content Include="obj\Debug\net10.0\rjsmcshtml.dswa.cache.json" />
    <Content Include="obj\Debug\net10.0\rjsmrazor.dswa.cache.json" />
    <Content Include="obj\Debug\net10.0\rpswa.dswa.cache.json" />
    <Content Include="obj\Debug\net10.0\scopedcss\bundle\CrudOperation.styles.css" />
    <Content Include="obj\Debug\net10.0\scopedcss\projectbundle\CrudOperation.bundle.scp.css" />
    <Content Include="obj\Debug\net10.0\scopedcss\Views\Shared\_Layout.cshtml.rz.scp.css" />
    <Content Include="obj\Debug\net10.0\staticwebassets.build.endpoints.json" />
    <Content Include="obj\Debug\net10.0\staticwebassets.build.json" />
    <Content Include="obj\Debug\net10.0\staticwebassets.development.json" />
    <Content Include="obj\Debug\net10.0\staticwebassets.references.upToDateCheck.txt" />
    <Content Include="obj\Debug\net10.0\staticwebassets.removed.txt" />
    <Content Include="obj\Debug\net10.0\staticwebassets.upToDateCheck.txt" />
    <Content Include="obj\project.assets.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
    <Folder Include="obj\Debug\net10.0\staticwebassets\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bin\Debug\net10.0\Azure.Core.dll" />
    <None Include="bin\Debug\net10.0\Azure.Identity.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\cs\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\de\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\es\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\fr\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\it\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\ja\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\ko\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\Microsoft.Build.Locator.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe.config" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\Microsoft.IO.Redist.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\Newtonsoft.Json.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\pl\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\pt-BR\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\ru\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\System.Buffers.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\System.Collections.Immutable.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\System.CommandLine.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\System.Memory.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\System.Numerics.Vectors.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\System.Runtime.CompilerServices.Unsafe.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\System.Threading.Tasks.Extensions.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\tr\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\zh-Hans\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-net472\zh-Hant\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-netcore\cs\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-netcore\de\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-netcore\es\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-netcore\fr\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-netcore\it\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-netcore\ja\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-netcore\ko\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-netcore\Microsoft.Build.Locator.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-netcore\Newtonsoft.Json.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-netcore\pl\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-netcore\pt-BR\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-netcore\ru\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-netcore\System.Collections.Immutable.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-netcore\System.CommandLine.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-netcore\tr\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-netcore\zh-Hans\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\BuildHost-netcore\zh-Hant\System.CommandLine.resources.dll" />
    <None Include="bin\Debug\net10.0\CrudOperation.dll" />
    <None Include="bin\Debug\net10.0\CrudOperation.exe" />
    <None Include="bin\Debug\net10.0\CrudOperation.pdb" />
    <None Include="bin\Debug\net10.0\cs\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\cs\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\cs\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\cs\Microsoft.CodeAnalysis.Workspaces.MSBuild.resources.dll" />
    <None Include="bin\Debug\net10.0\cs\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\cs\Microsoft.Data.SqlClient.resources.dll" />
    <None Include="bin\Debug\net10.0\de\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\de\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\de\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\de\Microsoft.CodeAnalysis.Workspaces.MSBuild.resources.dll" />
    <None Include="bin\Debug\net10.0\de\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\de\Microsoft.Data.SqlClient.resources.dll" />
    <None Include="bin\Debug\net10.0\es\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\es\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\es\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\es\Microsoft.CodeAnalysis.Workspaces.MSBuild.resources.dll" />
    <None Include="bin\Debug\net10.0\es\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\es\Microsoft.Data.SqlClient.resources.dll" />
    <None Include="bin\Debug\net10.0\fr\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\fr\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\fr\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\fr\Microsoft.CodeAnalysis.Workspaces.MSBuild.resources.dll" />
    <None Include="bin\Debug\net10.0\fr\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\fr\Microsoft.Data.SqlClient.resources.dll" />
    <None Include="bin\Debug\net10.0\Humanizer.dll" />
    <None Include="bin\Debug\net10.0\it\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\it\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\it\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\it\Microsoft.CodeAnalysis.Workspaces.MSBuild.resources.dll" />
    <None Include="bin\Debug\net10.0\it\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\it\Microsoft.Data.SqlClient.resources.dll" />
    <None Include="bin\Debug\net10.0\ja\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\ja\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\ja\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\ja\Microsoft.CodeAnalysis.Workspaces.MSBuild.resources.dll" />
    <None Include="bin\Debug\net10.0\ja\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\ja\Microsoft.Data.SqlClient.resources.dll" />
    <None Include="bin\Debug\net10.0\ko\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\ko\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\ko\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\ko\Microsoft.CodeAnalysis.Workspaces.MSBuild.resources.dll" />
    <None Include="bin\Debug\net10.0\ko\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\ko\Microsoft.Data.SqlClient.resources.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.AspNetCore.Authentication.JwtBearer.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.Bcl.AsyncInterfaces.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.Bcl.Cryptography.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.Build.Framework.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.CodeAnalysis.CSharp.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.CodeAnalysis.CSharp.Workspaces.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.CodeAnalysis.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.CodeAnalysis.Workspaces.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.CodeAnalysis.Workspaces.MSBuild.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.Data.SqlClient.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.EntityFrameworkCore.Abstractions.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.EntityFrameworkCore.Design.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.EntityFrameworkCore.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.EntityFrameworkCore.Relational.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.EntityFrameworkCore.SqlServer.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.Extensions.DependencyModel.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.Identity.Client.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.Identity.Client.Extensions.Msal.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.IdentityModel.Abstractions.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.IdentityModel.JsonWebTokens.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.IdentityModel.Logging.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.IdentityModel.Protocols.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.IdentityModel.Protocols.OpenIdConnect.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.IdentityModel.Tokens.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.SqlServer.Server.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.VisualStudio.SolutionPersistence.dll" />
    <None Include="bin\Debug\net10.0\Mono.TextTemplating.dll" />
    <None Include="bin\Debug\net10.0\Newtonsoft.Json.dll" />
    <None Include="bin\Debug\net10.0\pl\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\pl\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\pl\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\pl\Microsoft.CodeAnalysis.Workspaces.MSBuild.resources.dll" />
    <None Include="bin\Debug\net10.0\pl\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\pl\Microsoft.Data.SqlClient.resources.dll" />
    <None Include="bin\Debug\net10.0\pt-BR\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\pt-BR\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\pt-BR\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\pt-BR\Microsoft.CodeAnalysis.Workspaces.MSBuild.resources.dll" />
    <None Include="bin\Debug\net10.0\pt-BR\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\pt-BR\Microsoft.Data.SqlClient.resources.dll" />
    <None Include="bin\Debug\net10.0\runtimes\unix\lib\net9.0\Microsoft.Data.SqlClient.dll" />
    <None Include="bin\Debug\net10.0\runtimes\win-arm64\native\Microsoft.Data.SqlClient.SNI.dll" />
    <None Include="bin\Debug\net10.0\runtimes\win-x64\native\Microsoft.Data.SqlClient.SNI.dll" />
    <None Include="bin\Debug\net10.0\runtimes\win-x86\native\Microsoft.Data.SqlClient.SNI.dll" />
    <None Include="bin\Debug\net10.0\runtimes\win\lib\net9.0\Microsoft.Data.SqlClient.dll" />
    <None Include="bin\Debug\net10.0\ru\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\ru\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\ru\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\ru\Microsoft.CodeAnalysis.Workspaces.MSBuild.resources.dll" />
    <None Include="bin\Debug\net10.0\ru\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\ru\Microsoft.Data.SqlClient.resources.dll" />
    <None Include="bin\Debug\net10.0\System.ClientModel.dll" />
    <None Include="bin\Debug\net10.0\System.CodeDom.dll" />
    <None Include="bin\Debug\net10.0\System.Composition.AttributedModel.dll" />
    <None Include="bin\Debug\net10.0\System.Composition.Convention.dll" />
    <None Include="bin\Debug\net10.0\System.Composition.Hosting.dll" />
    <None Include="bin\Debug\net10.0\System.Composition.Runtime.dll" />
    <None Include="bin\Debug\net10.0\System.Composition.TypedParts.dll" />
    <None Include="bin\Debug\net10.0\System.Configuration.ConfigurationManager.dll" />
    <None Include="bin\Debug\net10.0\System.IdentityModel.Tokens.Jwt.dll" />
    <None Include="bin\Debug\net10.0\System.Memory.Data.dll" />
    <None Include="bin\Debug\net10.0\System.Security.Cryptography.ProtectedData.dll" />
    <None Include="bin\Debug\net10.0\tr\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\tr\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\tr\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\tr\Microsoft.CodeAnalysis.Workspaces.MSBuild.resources.dll" />
    <None Include="bin\Debug\net10.0\tr\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\tr\Microsoft.Data.SqlClient.resources.dll" />
    <None Include="bin\Debug\net10.0\zh-Hans\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\zh-Hans\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\zh-Hans\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\zh-Hans\Microsoft.CodeAnalysis.Workspaces.MSBuild.resources.dll" />
    <None Include="bin\Debug\net10.0\zh-Hans\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\zh-Hans\Microsoft.Data.SqlClient.resources.dll" />
    <None Include="bin\Debug\net10.0\zh-Hant\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\zh-Hant\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\zh-Hant\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\zh-Hant\Microsoft.CodeAnalysis.Workspaces.MSBuild.resources.dll" />
    <None Include="bin\Debug\net10.0\zh-Hant\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\zh-Hant\Microsoft.Data.SqlClient.resources.dll" />
    <None Include="obj\CrudOperation.csproj.nuget.g.props" />
    <None Include="obj\CrudOperation.csproj.nuget.g.targets" />
    <None Include="obj\Debug\net10.0\apphost.exe" />
    <None Include="obj\Debug\net10.0\compressed\07qllbce8h-{0}-356vix0kms-356vix0kms.gz" />
    <None Include="obj\Debug\net10.0\compressed\07y4hyszic-{0}-2z0ns9nrw6-2z0ns9nrw6.gz" />
    <None Include="obj\Debug\net10.0\compressed\0p0evhvyjv-{0}-46ein0sx1k-46ein0sx1k.gz" />
    <None Include="obj\Debug\net10.0\compressed\1hpxuj2tgd-{0}-dxx9fxp4il-dxx9fxp4il.gz" />
    <None Include="obj\Debug\net10.0\compressed\1lgcjeq78j-{0}-0i3buxo5is-0i3buxo5is.gz" />
    <None Include="obj\Debug\net10.0\compressed\23xqt0539i-{0}-fsbi9cje9m-fsbi9cje9m.gz" />
    <None Include="obj\Debug\net10.0\compressed\2yszalhkn3-{0}-d7shbmvgxk-d7shbmvgxk.gz" />
    <None Include="obj\Debug\net10.0\compressed\342zuep89q-{0}-nvvlpmu67g-nvvlpmu67g.gz" />
    <None Include="obj\Debug\net10.0\compressed\4bnmmtrmij-{0}-ag7o75518u-ag7o75518u.gz" />
    <None Include="obj\Debug\net10.0\compressed\4pm1vir2k1-{0}-83jwlth58m-83jwlth58m.gz" />
    <None Include="obj\Debug\net10.0\compressed\5cjq79sqmi-{0}-lzl9nlhx6b-lzl9nlhx6b.gz" />
    <None Include="obj\Debug\net10.0\compressed\5h01ln1yrs-{0}-s35ty4nyc5-s35ty4nyc5.gz" />
    <None Include="obj\Debug\net10.0\compressed\5kz8fnb0ci-{0}-y7v9cxd14o-y7v9cxd14o.gz" />
    <None Include="obj\Debug\net10.0\compressed\6usyxopkxp-{0}-06098lyss8-06098lyss8.gz" />
    <None Include="obj\Debug\net10.0\compressed\71kthsjj1q-{0}-r4e9w2rdcm-r4e9w2rdcm.gz" />
    <None Include="obj\Debug\net10.0\compressed\88x6ar5eoz-{0}-aexeepp0ev-aexeepp0ev.gz" />
    <None Include="obj\Debug\net10.0\compressed\9i37lrj1mi-{0}-493y06b0oq-493y06b0oq.gz" />
    <None Include="obj\Debug\net10.0\compressed\argk49z9da-{0}-c2oey78nd0-c2oey78nd0.gz" />
    <None Include="obj\Debug\net10.0\compressed\b435p34sd1-{0}-lcd1t2u6c8-lcd1t2u6c8.gz" />
    <None Include="obj\Debug\net10.0\compressed\bklqdf37t9-{0}-o1o13a6vjx-o1o13a6vjx.gz" />
    <None Include="obj\Debug\net10.0\compressed\c6geulyql0-{0}-wd71rk4eby-wd71rk4eby.gz" />
    <None Include="obj\Debug\net10.0\compressed\cc36p8f0ya-{0}-mrlpezrjn3-mrlpezrjn3.gz" />
    <None Include="obj\Debug\net10.0\compressed\dgwbf4rra8-{0}-jj8uyg4cgr-jj8uyg4cgr.gz" />
    <None Include="obj\Debug\net10.0\compressed\e10yezmv99-{0}-v0zj4ognzu-v0zj4ognzu.gz" />
    <None Include="obj\Debug\net10.0\compressed\et7yx9g3ut-{0}-87fc7y1x7t-87fc7y1x7t.gz" />
    <None Include="obj\Debug\net10.0\compressed\fcbql58zfa-{0}-j5mq2jizvt-j5mq2jizvt.gz" />
    <None Include="obj\Debug\net10.0\compressed\fexegg267g-{0}-c2jlpeoesf-c2jlpeoesf.gz" />
    <None Include="obj\Debug\net10.0\compressed\gfwcblb508-{0}-h1s4sie4z3-h1s4sie4z3.gz" />
    <None Include="obj\Debug\net10.0\compressed\gkl97zilof-{0}-vr1egmr9el-vr1egmr9el.gz" />
    <None Include="obj\Debug\net10.0\compressed\gthm9cvwgy-{0}-6cfz1n2cew-6cfz1n2cew.gz" />
    <None Include="obj\Debug\net10.0\compressed\h1uw8t6peu-{0}-xtxxf3hu2r-xtxxf3hu2r.gz" />
    <None Include="obj\Debug\net10.0\compressed\i5bmlyscfl-{0}-b9sayid5wm-b9sayid5wm.gz" />
    <None Include="obj\Debug\net10.0\compressed\ib2b8xek1y-{0}-pk9g2wxc8p-pk9g2wxc8p.gz" />
    <None Include="obj\Debug\net10.0\compressed\j0fcspgiv8-{0}-b7pk76d08c-b7pk76d08c.gz" />
    <None Include="obj\Debug\net10.0\compressed\jms50u9v21-{0}-kbrnm935zg-kbrnm935zg.gz" />
    <None Include="obj\Debug\net10.0\compressed\k2mahgbxoa-{0}-khv3u5hwcm-khv3u5hwcm.gz" />
    <None Include="obj\Debug\net10.0\compressed\lurg4owl5m-{0}-wd71rk4eby-wd71rk4eby.gz" />
    <None Include="obj\Debug\net10.0\compressed\mudv24nhs9-{0}-tdbxkamptv-tdbxkamptv.gz" />
    <None Include="obj\Debug\net10.0\compressed\n5ketmopnv-{0}-pj5nd1wqec-pj5nd1wqec.gz" />
    <None Include="obj\Debug\net10.0\compressed\oo2oyifwxp-{0}-erw9l3u2r3-erw9l3u2r3.gz" />
    <None Include="obj\Debug\net10.0\compressed\oy3mkfhnbf-{0}-bqjiyaj88i-bqjiyaj88i.gz" />
    <None Include="obj\Debug\net10.0\compressed\pmhxfg1dzs-{0}-63fj8s7r0e-63fj8s7r0e.gz" />
    <None Include="obj\Debug\net10.0\compressed\q5fepvl64o-{0}-cosvhxvwiu-cosvhxvwiu.gz" />
    <None Include="obj\Debug\net10.0\compressed\qc81ubg798-{0}-0j3bgjxly4-0j3bgjxly4.gz" />
    <None Include="obj\Debug\net10.0\compressed\r20az7satl-{0}-iovd86k7lj-iovd86k7lj.gz" />
    <None Include="obj\Debug\net10.0\compressed\s0x5p4sbz1-{0}-ft3s53vfgj-ft3s53vfgj.gz" />
    <None Include="obj\Debug\net10.0\compressed\s1l53vgj0u-{0}-notf2xhcfb-notf2xhcfb.gz" />
    <None Include="obj\Debug\net10.0\compressed\sjxfjt8983-{0}-61n19gt1b8-61n19gt1b8.gz" />
    <None Include="obj\Debug\net10.0\compressed\snq3q2btoc-{0}-x0q3zqp4vz-x0q3zqp4vz.gz" />
    <None Include="obj\Debug\net10.0\compressed\sscyenduzy-{0}-muycvpuwrr-muycvpuwrr.gz" />
    <None Include="obj\Debug\net10.0\compressed\tfngqkg5i2-{0}-hrwsygsryq-hrwsygsryq.gz" />
    <None Include="obj\Debug\net10.0\compressed\unua2pclxv-{0}-ttgo8qnofa-ttgo8qnofa.gz" />
    <None Include="obj\Debug\net10.0\compressed\vttiemcuio-{0}-rzd6atqjts-rzd6atqjts.gz" />
    <None Include="obj\Debug\net10.0\compressed\wymt2ogm1b-{0}-ub07r2b239-ub07r2b239.gz" />
    <None Include="obj\Debug\net10.0\compressed\x0c9xcxn0v-{0}-ee0r1s7dh0-ee0r1s7dh0.gz" />
    <None Include="obj\Debug\net10.0\compressed\x1h77z36bf-{0}-fvhpjtyr6v-fvhpjtyr6v.gz" />
    <None Include="obj\Debug\net10.0\compressed\x7ie7bpg0c-{0}-k8d9w2qqmf-k8d9w2qqmf.gz" />
    <None Include="obj\Debug\net10.0\compressed\xczbqhip93-{0}-jd9uben2k1-jd9uben2k1.gz" />
    <None Include="obj\Debug\net10.0\compressed\xw0nplgymm-{0}-ausgxo2sd3-ausgxo2sd3.gz" />
    <None Include="obj\Debug\net10.0\compressed\xw4kc5bm16-{0}-6pdc2jztkx-6pdc2jztkx.gz" />
    <None Include="obj\Debug\net10.0\compressed\yanb5pmyrp-{0}-4v8eqarkd7-4v8eqarkd7.gz" />
    <None Include="obj\Debug\net10.0\compressed\ydcutkhjf7-{0}-37tfw0ft22-37tfw0ft22.gz" />
    <None Include="obj\Debug\net10.0\compressed\ysq4abmode-{0}-mlv21k5csn-mlv21k5csn.gz" />
    <None Include="obj\Debug\net10.0\compressed\ztfuxwjkyl-{0}-47otxtyo56-47otxtyo56.gz" />
    <None Include="obj\Debug\net10.0\CrudOper.3BBD6E1A.Up2Date" />
    <None Include="obj\Debug\net10.0\CrudOperation.AssemblyInfoInputs.cache" />
    <None Include="obj\Debug\net10.0\CrudOperation.assets.cache" />
    <None Include="obj\Debug\net10.0\CrudOperation.csproj.AssemblyReference.cache" />
    <None Include="obj\Debug\net10.0\CrudOperation.csproj.BuildWithSkipAnalyzers" />
    <None Include="obj\Debug\net10.0\CrudOperation.csproj.CoreCompileInputs.cache" />
    <None Include="obj\Debug\net10.0\CrudOperation.dll" />
    <None Include="obj\Debug\net10.0\CrudOperation.GeneratedMSBuildEditorConfig.editorconfig" />
    <None Include="obj\Debug\net10.0\CrudOperation.genruntimeconfig.cache" />
    <None Include="obj\Debug\net10.0\CrudOperation.MvcApplicationPartsAssemblyInfo.cache" />
    <None Include="obj\Debug\net10.0\CrudOperation.pdb" />
    <None Include="obj\Debug\net10.0\CrudOperation.RazorAssemblyInfo.cache" />
    <None Include="obj\Debug\net10.0\refint\CrudOperation.dll" />
    <None Include="obj\Debug\net10.0\ref\CrudOperation.dll" />
    <None Include="obj\Debug\net10.0\staticwebassets.build.json.cache" />
    <None Include="obj\Debug\net10.0\swae.build.ex.cache" />
    <None Include="obj\project.nuget.cache" />
  </ItemGroup>

</Project>
